@startuml process-view
autonumber

actor "Patient" as Patient
participant SARM as "SARM" <<system (C4)>>

activate Patient

    Patient -> SARM : asks to update my user patient profile
    
    activate SARM

        SARM --> Patient : confirms the update

    deactivate SARM

deactivate Patient

@enduml