@startuml process-view
autonumber

actor "Doctor" as Doctor
participant SARM as "SARM" <<system (C4)>>

activate Doctor

    Doctor -> SARM : asks to list operation requests
    
    activate SARM

        SARM --> Doctor: shows operation requests
        
    deactivate SARM

deactivate Doctor

@enduml