@startuml level3

autonumber

actor "User" as UserP
participant "RequestOperationsController" as Controller <<Controller>>
participant "RequestOperationService" as Service <<Service>>
participant "Patient" as Patient <<Domain>>
participant "OperationRequest" as OperationRequest <<Domain>>
participant "OperationRequestDto" as OperationRequestDto <<Domain>>
database "IStaffRepository" as StaffRepository <<Domain>>
database "IPatientRepository" as PatientRepository <<Domain>>
database "IOperationRequestRepository" as OperationRequestRepository <<Domain>>

activate UserP
UserP->Controller: POST /api/operationrequests
activate Controller

    Controller->Service:addgetDoctorByIdAsync(operationRequestDto)
    activate Service

        Service -> StaffRepository:getDoctorByIdAsync(operationRequestDto.doctorID)
        activate StaffRepository

            StaffRepository-->Service:doctor
        deactivate StaffRepository
        

        alt doctor.specialization == operationType.specialization then
        

        Service->OperationRequest:create(operationRequestDto.PatientId, operationRequestDto.doctorID, operationRequestDto.OperationTypeId, operationRequestDto.deadline, operationRequestDto.priority)
        activate OperationRequest

            OperationRequest-->Service:operationRequest
        deactivate OperationRequest

        Service->OperationRequestRepository:addAsync(operationRequest)
        activate OperationRequestRepository

            OperationRequestRepository-->Service:operationRequest
        deactivate OperationRequestRepository

        Service->Patient:updateAppointmentHistory(operationRequest)

        Service->PatientRepository:updateAsync(patient)
        activate PatientRepository

            PatientRepository-->Service:patient
        deactivate PatientRepository

        Service->OperationRequestDto:create(PatientId, DoctorId, OperationType,Deadline, Priority)
        activate OperationRequestDto

            OperationRequestDto-->Service:operationRequestDto
        deactivate OperationRequestDto
        Service --> Controller:operationRequestDto

        UserP<--Controller:201 created
        else
            Controller<--Service:BusinessRuleValidationException
        deactivate Service
        UserP<--Controller:403 Forbidden
    deactivate Controller


    end alt


@enduml