@startuml level3

autonumber

actor "Doctor" as Doctor
participant "OperationRequestsController" as Controller <<Controller>>
participant "OperationRequestService" as Service <<Service>>
database "IOperationRequestRepository" as OperationRequestRepository <<Domain>>

activate Doctor
Doctor->Controller: GET /api/operationrequests/filter
    activate Controller
        Controller->Service:GetOperationRequestsAsync(patientId, operationTypeId, priority, status)
        activate Service
                Service ->  OperationRequestRepository : GetOperationRequestsAsync(patientId, operationTypeId, priority, status)

                activate OperationRequestRepository

                    OperationRequestRepository -->  Service : operationRequests

                deactivate OperationRequestRepository

                Service -->  Controller : operationRequestsDto
        deactivate Service
        Doctor<--Controller:200 OK
    deactivate Controller
@enduml