@startuml process-view-2
autonumber

actor "Admin" as Admin
participant "StaffsController" as Controller <<Controller>>
participant "StaffService" as Service <<Service>>
database "IStaffRepository" as Repository <<Domain>>

activate Admin
        Admin -> Controller : GET /api/staffss/filter
        activate Controller 
            Controller -> Service : GetOperationTypes(filters)
            activate Service
                Service ->  Repository : GetStaffsAsync(filters)
                activate Repository
                    Repository -->  Service : staffs
                deactivate Repository
                Service -->  Controller : staffsDto
            deactivate Service
        Controller --> Admin : 200 OK
    deactivate Controller
deactivate Admin


@enduml