@startuml mapping
top to bottom direction

package " " <<SARM>>{
    folder "Backend Data Management" as Backend {

    }

    folder "Frontend" as Frontend{

    }

    folder "BCP" as BCP{

    }

    folder "GDPR" as GDPR{

    }

    folder  "Planning" as Planning {

    }
}

Frontend <.. Backend
Backend <.. Planning
Planning <.. Backend
BCP <.. Backend
Backend <.. GDPR


interface "API" as API
interface "UI" as UI
interface "Auth0 API" as A0API
interface "SMTP Office 365" as SMTP_Office_365

component "SARM" <<component>> <<C4 System>> {
    portin " " as SARMPI
    portin " " as SARMPIUI
    portout " " as SARMPO1
    portout " " as SARMPO2

    interface "Backend Data Management API" as BACKENDAPI

    component "Backend Data Management" as BEDM <<component>> {
        portin " " as BackendPI
        portout " " as BackendPO1
        portout " " as BackendPO2
        portout " " as BackendPO3
        portout " " as BackendPO4
        portin " " as BackendPI2
    }

    component "Frontend" as FE <<component>> {
        portin " " as FrontendINUI
        portout " " as FrontendOutUI2
    }

    interface "Planning API" as PLANNINGAPI

    component "Planning" as PL <<component>> {
        portin " " as PLANNINGINUI
        portout " " as PLANNINGOutUI
    }

    interface "GDPR API" as GDPR_API

    component "GDPR" as GDPR_ <<component>> {
        portin " " as GDPRINUI
    }
    
    component "BCP" as BCP_ <<component>> {
        portout " " as BCPOutUI
    }

}

UI -- SARMPIUI
SARMPIUI --- FrontendINUI
FrontendOutUI2 --( BACKENDAPI
BackendPI2 -U- BACKENDAPI

GDPRINUI -U- GDPR_API
BackendPO3 --( GDPR_API

PLANNINGINUI -U- PLANNINGAPI
BackendPO4 --( PLANNINGAPI
PLANNINGOutUI --( BACKENDAPI

BCPOutUI --( BACKENDAPI

API -- SARMPI
SARMPO1 -u--( A0API
SARMPI -- BackendPI
SARMPO1 -- BackendPO1

SARMPO2 -- BackendPO2
SARMPO2 --( SMTP_Office_365

BCP ...> BCP_ : <<manifest>>
GDPR ...> GDPR_ : <<manifest>>
Backend ...> BEDM : <<manifest>>
Frontend ...> FE : <<manifest>>
Planning ...> PL : <<manifest>>

@enduml