@startuml process-view2

autonumber

actor "Doctor" as UserP
participant "OperationRequestsController" as Controller <<Controller>>
participant "OperationRequestService" as Service <<Service>>
participant "OperationRequest" as OperationRequest <<Domain>>
participant "OperationRequestDto" as OperationRequestDto <<Domain>>
database "IUserRepository" as UserRepository <<Domain>>
database "IOperationRequestRepository" as OperationRequestRepository <<Domain>>

activate UserP
    UserP->Controller:PUT /api/operationRequest/{id}

activate Controller

    Controller->Service:UpdateOperationRequestAsync(id,operationRequestUpdateDto)
    activate Service

        Service->OperationRequestRepository:getById(operationRequestId)
        activate OperationRequestRepository

            OperationRequestRepository-->Service:operationRequest
        deactivate OperationRequestRepository

        alt operationRequest==null then
            Service-->Controller:BusinessRuleValidationException
            Controller-->UserP:404 NOT FOUND
        else

        alt operationRequest.priority!=null then
        Service->OperationRequest:ChangePriority(operationRequestUpdateDto.Priority)
        end alt

        alt operationRequest.deadline!=null then
        Service->OperationRequest:ChangeDeadline(operationRequestUpdateDto.Deadline)
        end alt

        Service->OperationRequestRepository:UpdateAsync(operationRequest)

        Service->OperationRequestDto:create(PatientId, DoctorId, OperationType,Deadline, Priority, Status)
        activate OperationRequestDto

            OperationRequestDto-->Service:operationRequestDto
        deactivate OperationRequestDto

        Service --> Controller:operationRequestDto
    deactivate Service

    UserP<--Controller:200 OK
deactivate Controller
end alt


@enduml