@startuml process-view
autonumber
actor "Admin" as adm
participant "SARM" as sarm <<system (C4)>>

activate adm
    adm -> sarm : asks to edit a staff profile
    activate sarm
        sarm --> adm : confirms the edition of the staff profile
    deactivate sarm
deactivate adm

@endum