@startuml process-view
autonumber

actor "Admin" as Admin
participant SARM as "SARM" <<system (C4)>>

activate Admin

    Admin -> SARM : asks to add new type of operation
    
    activate SARM

        SARM --> Admin : confirms the addition

    deactivate SARM

deactivate Admin

@enduml