@startuml process-view
autonumber

actor "Patient" as Patient
participant SARM as "SARM" <<system (C4)>>

activate Patient

    Patient -> SARM : asks to register for the healthcare application
    
    activate SARM

        SARM --> Patient : confirms the registration

    deactivate SARM

deactivate Patient

@enduml