@startuml process-view

actor "Admin" as ADM
participant "Server" as Server
participant "Database" as Database

activate ADM
ADM-> Server : POST /api/patients
activate Server
    Server -> Database : save patient
    activate Database
        Database --> Server : patient
    deactivate Database
    ADM <-- Server : 201 Created
deactivate Server
deactivate ADM

@enduml