@startuml
top to bottom direction

folder "SARM" <<folder>>{

    folder "Backend Data Management" as BackendDataManagement{

    }

    folder "Frontend" as FrontendDataManagement{
        
    }

    folder "Planning" as Planning{
        
    }

}

BackendDataManagement <.. FrontendDataManagement
BackendDataManagement ..> Planning
FrontendDataManagement .r.> Planning

@enduml