@startuml implementation-view
top to bottom direction

package " " <<SARM>>{
    folder "Backend Data Management" as Backend {

    }

    folder "Frontend" as Frontend{

    }

    folder "BCP" as BCP{

    }

    folder "GDPR" as GDPR{

    }

    folder  "Planning" as Planning {

    }

    folder  "Backend Node" as BackendNode {

    }
}

Frontend <.. Backend
Frontend <.. BackendNode
Backend <.. BackendNode
Backend <.. Planning
Planning <.. Backend
BCP <.. Backend
Backend <.. GDPR

@enduml