@startuml logic-view
top to bottom direction

interface "API" as API
interface "Auth0 API" as A0API
interface "SMTP Office 365" as SMTP_Office_365

component "SARM" <<component>> <<C4 System>> {
    portin " " as SARMPI
    portout " " as SARMPO1
    portout " " as SARMPO2

    component "Backend Data Management" <<component>> {
        portin " " as BackendPI
        portout " " as BackendPO1
        portout " " as BackendPO2
    }

}

API -- SARMPI
SARMPO1 --( A0API
SARMPI -- BackendPI
SARMPO1 -- BackendPO1

SARMPO2 -- BackendPO2
SARMPO2 -u-( SMTP_Office_365

@enduml