@startuml physical-view

node "localhost: " as LOCALHOST {

  component "Frontend" as Frontend <<component>>{
  }

  component "Planning" as Planning <<component>>  { 
  }
}

node "Server 2: vs1422" as Server {
  
  component "Backend Data Management" as BackendDataManagement <<component>> {
  }
}

node "Server 1: vs1372" as Server2 {
    database "Mysql" as Database <<database>> {
  }
}

LOCALHOST -u- Server : http/s
LOCALHOST -- Server2 : TCP/IP

@enduml