@startuml process-view2

autonumber

actor "Admin" as UserP
participant "UsersController" as Controller <<Controller>>
participant "UserService" as Service <<Service>>
participant "User" as User <<Domain>>
participant "UserDTO" as UserDto <<Domain>>
database "IUserRepository" as UserRepository <<Domain>>

activate UserP
    UserP->Controller:POST /api/users

activate Controller

    Controller->Service:addBackofficeUserAsync(creatingUserDto)
    activate Service

        Service->UserRepository:CountBackofficeUsersAsync()
        activate UserRepository

            UserRepository-->Service:count
        deactivate UserRepository

        Service -> User:create(Username,creatingUserDto.email,creatingUserDto.role)
        activate User

            User-->Service:user
        deactivate User

        Service->UserRepository:addAsnc(user)
        activate UserRepository

            UserRepository-->Service:user
        deactivate UserRepository

        note right of Service: Create User in Auth0

        Service->UserDto:create(user.Username,user.email,user.Role)
        activate UserDto

            UserDto-->Service:userDto
        deactivate UserDto


        Service --> Controller:userDto
    deactivate Service

    UserP<--Controller:201 Created
deactivate Controller

@enduml