@startuml process-view

autonumber

actor Admin as  "Admin"
participant "Server" as Server
participant "Database" as Database

activate Admin
    Admin->Server:POST /api/users
    activate Server
        Server->Database:CountBackofficeUserAsync()
        activate Database

            Server<-Database:count
        deactivate Database

        Server->Database:addAsync(User)
        activate Database

            Server<-Database:user
        deactivate Database

        note right of Server: Create User in Auth0

        Admin<-Server:201 Created
    deactivate Server
deactivate Admin

@enduml