@startuml process-view
autonumber

actor "Admin" as adm
participant "SARM" as sarm <<system (C4)>>

activate adm
    adm -> sarm : asks to list/search a patient profile
    activate sarm
        sarm --> adm : list of profiles
    deactivate sarm
deactivate adm

@endum