@startuml logic-view
top to bottom direction

interface "API" as API
interface "Auth0 API" as A0API
interface "SMTP Office 365" as SMTP_Office_365
interface "UI" as UI

component "SARM" <<component>> <<C4 System>> {
    portin " " as PI
    portin " " as PIUI
    portout " " as PI1
    portout " " as PI2
}
UI -- PIUI
API -- PI
PI1 --( A0API
PI2 --( SMTP_Office_365

@enduml