@startuml level3

participant "UserController" as Controller <<Controller>>
participant "UserService" as Service <<Service>>
database "UserRepository" as UserRepository <<domain>>

?o->Controller:GET /api/users/login
activate Controller

    Controller->Service:UserLoginAsync(username,password)
    activate Service

        

        /'
        Service->Auth:verifyLogin(user,password)
        activate Auth

            Auth-->Service:result
        deactivate Auth
        '/

        Service-->Controller:message
    deactivate Service
    <--Controller:message
deactivate Controller

@enduml