@startuml level3

actor "User" as UserP
participant "UsersController" as Controller <<Controller>>
participant "UserService" as Service <<Service>>
database "UserRepository" as UserRepository <<domain>>

activate UserP
UserP->Controller:GET /api/users/login
activate Controller

    Controller->Service:UserLoginAsync(username,password)
    activate Service

        

        /'
        Service->Auth:verifyLogin(user,password)
        activate Auth

            Auth-->Service:result
        deactivate Auth
        '/

        Service-->Controller:message
    deactivate Service
    UserP<--Controller:201 autenticated
deactivate Controller

@enduml