@startuml process-view
autonumber

actor "BackofficeUser" as Patient
participant "Server" as Server

activate Patient

    Patient-> Server : POST /api/users/login

    activate Server

        Note  right of Server: Login to the auth0 api

        Patient <-- Server : 200 OK

    deactivate Server
deactivate Patient

@enduml