@startuml process-view

actor "Admin" as Adm

Adm -> Server : POST /api/users/patients
activate Server

    Server -> Database : get user
    activate Database
        Database --> Server : user
    deactivate Database
    Server -> Database : save staff
    activate Database
        Database --> Server : staff
    deactivate Database
    Server --> Admin : 201 Created
deactivate Server

@enduml