@startuml process-view-2
autonumber

actor "Admin" as Adm
participant "StaffsController" as Controller <<Contreoller>>
participant "StaffService" as Service <<Service>>
participant "User" as User <<Domain>>
participant "Staff" as Staff <<Domain>>
participant "StaffDto" as StaffDto <<Domain>>
database "IUserRepository" as UserRepository <<Domain>>
database "IStaffRepository" as StaffRepository <<Domain>>


Adm -> Controller : POST /api/staffs
activate Controller
    Controller -> Service : createStaffProfileAsync(creatingStaffDto)
    activate Service
        Service -> UserRepository : GetByEmailAsync(creatingStaffDto.email)
        activate UserRepository
            UserRepository --> Service : user
        deactivate UserRepository
alt user == null
        Service --> Controller : NotFoundException
    Controller --> Adm : 404 Not Found
end alt
        Service -> Staff : create(creatingStaffDto, user)
        activate Staff
            Staff --> Service : staff
        deactivate Staff
        Service -> StaffRepository : addAsync(staff)
        activate StaffRepository
            StaffRepository --> Service : staff
        deactivate StaffRepository
        Service -> StaffDto : create(staff)
        activate StaffDto
            StaffDto --> Service : staffDto
        deactivate StaffDto
        Service --> Controller : staffDto
    deactivate Service
    Controller --> Adm : 201 Created
deactivate Controller

@enduml