@startuml process-view
autonumber

actor "Admin" as Adm

activate Adm
    Adm -> Server : POST /api/staffs
    activate Server
        Server -> Database : get user
        activate Database
            Database --> Server : user
        deactivate Database
        Server -> Database : get specialization
        activate Database
            Database --> Server : specialization
        deactivate Database
        Server -> Database : save staff
        activate Database
            Database --> Server : staff
        deactivate Database
        Server --> Adm : 201 Created
    deactivate Server
deactivate Adm

@enduml