@startuml process-view

actor "BackofficeUser" as User
participant SYS as "SARM" <<C4:System>>

activate User

    User -> SYS : Asks to reseat the password
    activate SYS
        
        SYS-->User: Confirmation of password reseated
    deactivate SYS
deactivate User

@enduml