@startuml process-view
autonumber

actor "Admin" as adm
participant "SARM" as sarm <<system (C4)>>

activate adm
    adm -> sarm : asks to edit a patient profile
    activate sarm
        sarm --> adm : confirms the profile edition
    deactivate sarm
deactivate adm

@endum