@startuml process-view

actor "Admin" as Admin
participant SYS as "SARM" <<C4:System>>

activate Admin
Admin->SYS:POST /api/users
activate SYS

    SYS->SYS:addBackofficeUserAsync(creatingUserDto)

    Admin<--SYS:201 CREATED
deactivate SYS
deactivate Admin
@enduml