@startuml process-view

actor "Admin" as adm
participant "Server" as srv
participant "Database" as db

activate adm
    adm -> srv : DELETE /api/patients/{id}
    activate srv
        srv -> db : get patient
        activate db
            db --> srv : patient
        alt user!=null
                db --> srv : user
                srv -> db : delete user
                Note  right of srv: Delete user in the auth0 api
        end alt
        deactivate db
        srv -> db : save anonymized patient data

        activate db

            db --> srv : anonymized patient data

        deactivate db
        srv -> db : delete patient
        srv --> adm : 200 OK
    deactivate srv
deactivate adm

@enduml