@startuml process-view
autonumber

actor "Patient" as Patient
participant "Server" as Server
participant "Database" as Database

activate Patient

    Patient-> Server : DELETE /api/users/patients/{username}

    activate Server

        Server -> Database : get user by id
        
        activate Database

            Database --> Server : user

        deactivate Database

        Server -> Database : get patient by user id
        
        activate Database

            Database --> Server : patient

        deactivate Database

        Server -> Database : remove user

        Server -> Database : remove patient

        Note  right of Server: Delete user in the auth0 api

        Patient <-- Server : 200 OK

    deactivate Server
deactivate Patient

@enduml