@startuml process-view
autonumber

actor "Patient" as Patient
participant BackendDataManagement as "Backend Data Management" <<system (C4)>>

activate Patient
    Patient -> BackendDataManagement : PUT /api/users/patients/{username}
    activate BackendDataManagement

        BackendDataManagement -> BackendDataManagement : updateUserPatient(username,updateUserPatientDto)

        Patient <-- BackendDataManagement : 200 OK
    deactivate BackendDataManagement

deactivate Patient

@enduml