@startuml process-view
autonumber

actor "Patient" as Patient
participant BackendDataManagement as "Backend Data Management" <<system (C4)>>

activate Patient

    Patient -> BackendDataManagement : POST /api/users/patients/request-delete/{username}
    
    activate BackendDataManagement

        BackendDataManagement -> BackendDataManagement : RequestDeleteUserPatient(username)

        Patient <-- BackendDataManagement : 200 OK
    deactivate BackendDataManagement

    Patient -> BackendDataManagement : GET api/users/patients/confirm-delete/{username}
    activate BackendDataManagement

        BackendDataManagement -> BackendDataManagement : DeleteUserPatient(username)

        Patient <-- BackendDataManagement : 200 OK
    deactivate BackendDataManagement

deactivate Patient

@enduml