@startuml process-view
autonumber

actor "Patient" as Patient
participant BackendDataManagement as "Backend Data Management" <<system (C4)>>

activate Patient
    Patient -> BackendDataManagement : POST /api/users/patients
    activate BackendDataManagement

        BackendDataManagement -> BackendDataManagement : registerUserPatient(creatingUserDto)

        Patient <-- BackendDataManagement : 201 Created
    deactivate BackendDataManagement

deactivate Patient

@enduml