@startuml process-view
autonumber

actor Admin as  "Admin"
participant "Server" as Server
participant "Database" as Database

activate Admin
    Admin-> Server : POST /api/operationtypes

    activate Server

        Server -> Database : save operation type
        
        activate Database

            Database --> Server : operation type

        deactivate Database

        loop for each staffSpecialization

            Server -> Database : get specialization by id
            
            activate Database

                Database --> Server : specialization

            deactivate Database

            Server -> Database : save operation type specialization
        end 

        Admin <-- Server : 201 Created

    deactivate Server
deactivate Admin
@enduml