@startuml process-view-2
autonumber

actor "Admin" as Admin
participant "OperationTypesController" as Controller <<Controller>>
participant "OperationTypeService" as Service <<Service>>
participant "OperationType" as OperationType <<Domain>>
participant "OperationTypeDto" as OperationTypeDto <<Domain>>
participant "OperationTypeSpecialization" as OperationTypeSpecialization <<Domain>>
database "IOperationTypeRepository" as Repository <<Domain>>
database "SpecializationRepository" as SpecializationRepository <<Domain>>
database "IOperationTypeSpecializationRepository" as OperationTypeSpecializationRepository <<Domain>>

activate Admin
    Admin-> Controller : POST /api/operationtypes

    activate Controller

        Controller -> Service : AddAsync(creatingOperationTypeDto)

        activate Service

            Service -> OperationType : create(creatingOperationTypeDto.Name,creatingOperationTypeDto.EstimatedDuration,creatingOperationTypeDto.AnesthesiaTime,creatingOperationTypeDto.CleaningTime,creatingOperationTypeDto.SurgeryTime)

            activate OperationType

                OperationType --> Service : operationType

            deactivate OperationType

            Service  -> Repository : AddAsync(operationType)

            activate Repository

                Repository --> Service : operationType

            deactivate Repository

            loop for each staffSpecialization

                Service -> SpecializationRepository : GetByIdAsync(specializationId)

                activate SpecializationRepository

                    SpecializationRepository --> Service : specialization

                deactivate SpecializationRepository

                alt specialization == null 

                    Service --> Controller : NullReferenceException

                    Admin <-- Controller : 404 Not Found

                else 
                
                    Service -> OperationTypeSpecialization : create(operationType,specialization,staffSpecialization.NumberOfStaff)

                    activate OperationTypeSpecialization

                        OperationTypeSpecialization --> Service : operationTypeSpecialization

                    deactivate OperationTypeSpecialization

                    Service  -> OperationTypeSpecializationRepository : AddAsync(operationTypeSpecialization)

                end

            end

            Service -> OperationTypeDto : create(OperationTypeId,Name,EstimatedDuration,AnesthesiaTime,CleaningTime,SurgeryTime)

            activate OperationTypeDto

                OperationTypeDto --> Service : operationTypeDto

            deactivate OperationTypeDto

            Service --> Controller : operationTypeDto

        deactivate Service

        Admin <-- Controller : 201 Created

    deactivate Controller

deactivate Admin


@enduml