@startuml process-view
autonumber
skinparam DefaultTextAlignment center
actor Admin as "Admin"
box "<<system (C4)>>\nFrontend"#LightBlue
    participant ComponentUI as "UI Component" <<component (C4)>>
    participant Component as "Component" <<component (C4)>>
    participant SRV as "Service" <<component (C4)>>
    participant HTTP as "HTTP" <<component (C4)>>
end box

box "<<system (C4)>>\nBackend Data Management"
  participant BackendDataManagement as "Backend Data Management" <<component (C4)>>
end box

activate Admin
    Admin -> ComponentUI : asks to list staff profiles
    activate ComponentUI
        ComponentUI -> Component : list staff profiles
        activate Component
            Component -> SRV : list staff profiles
            activate SRV
                SRV -> HTTP : get('/staffs/filter')
                activate HTTP
                    HTTP -> BackendDataManagement : GET /staffs/filter
                    activate BackendDataManagement
                        BackendDataManagement --> HTTP : 200 (staffs)
                    deactivate BackendDataManagement
                    HTTP --> SRV : staffs
                deactivate HTTP
                SRV --> Component : staffs
            deactivate SRV
            Component --> ComponentUI : staffs
        deactivate Component
    Admin <-- ComponentUI : shows staffs
    deactivate ComponentUI
deactivate Admin

@enduml