@startuml process-view
autonumber

actor "Admin" as Admin
participant SARM as "SARM" <<system (C4)>>

activate Admin
    Admin -> SARM : asks to edit an operation type
    activate SARM
        SARM --> Admin : asks to input data
    deactivate SARM
    Admin -> SARM : inputs data
    activate SARM 
        SARM --> Admin: shows success message
    deactivate SARM
deactivate Admin

@enduml