@startuml process-view
autonumber

actor "Admin" as Admin
participant SARM as "SARM" <<system (C4)>>

activate Admin

    Admin -> SARM : asks to remove operation type

    activate SARM

        SARM --> Admin : confirms the remove

    deactivate SARM

deactivate Admin

@enduml