@startuml process-view
autonumber

actor "Admin" as adm
participant "Server" as srv
participant "Database" as db

activate adm
    adm -> srv : PUT /api/staffs/{id}
    activate srv
        srv -> db : get staff
        activate db
            db --> srv : staff
        deactivate db
alt
        srv -> db : add availability slot
        activate db
            db --> srv : availability slot
        deactivate db
end alt
alt
        srv -> db : remove availability slot
end alt
        srv -> db : update staff
        activate db
            db --> srv : staff
        deactivate db
        srv --> adm : 200 OK
    deactivate srv
deactivate adm


@enduml