@startuml Domain Model
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0

skinparam packageStyle rectangle

package "<<aggregate>> User"{
    
    entity User <<entity>> <<root>>{

    }
    class Username <<Value Object>>{

    }
    
    enum Role <<Value Object>> {
        ADMIN
        DOCTOR
        NURSE
        TECHNICIAN
        PATIENT
    }

    class Email  <<Value Object>> {
    }

}

package "<<aggregate>> Patient"{

    entity Patient <<entity>> <<root>>{
    }

    class PatientFirstName <<Value Object>>{

    }

    class PatientLastName <<Value Object>>{
        
    }

    class PatientFullName <<Value Object>>{
        
    }
    
    class DateOfBirth <<Value Object>>{
        
    }

    class Gender <<Value Object>>{
        
    }

    class MedicalRecordNumber <<Value Object>>{
        
    }

    entity PatientContactInformation <<Value Object>>{
        
    }

    class PatientEmail <<Value Object>>{
        
    }

    class PatientPhone <<Value Object>>{
        
    }

    class MedicalConditions <<Value Object>>{
        
    }

    class EmergencyContact <<Value Object>>{
        
    }

    class AppointmentHistory <<Value Object>>{
        
    }


}

package "<<aggregate>> Staff"{

    entity Staff <<entity>> <<root>>{
    }

    class StaffFirstName <<Value Object>>{

    }

    class StaffLastName <<Value Object>>{
        
    }

    class StaffFullName <<Value Object>>{
        
    }

    class LicenseNumber <<Value Object>>{
        
    }

    class AvailabilitySlots <<Value Object>>{
        
    }

    entity StaffContactInformation <<Value Object>>{
        
    }

    class StaffEmail <<Value Object>>{
        
    }

    class StaffPhone <<Value Object>>{
        
    }
}

package "<<aggregate>> OperationRequest"{

    entity OperationRequest <<entity>> <<root>>{
    }

    class OperationRequestId <<Value Object>>{
        
    }

    class DeadlineDate <<Value Object>>{
        
    }

    enum Priority <<Value Object>>{
        HIGH
        MEDIUM
        LOW
    }

}

package "<<aggregate Specialization>> "{

    entity Specialization <<entity>> <<root>>{
    }

    class SpecializationId <<Value Object>>{
        
    }

    class SpecializationName <<Value Object>>{
        
    }
}

package "<<aggregate>> OperationType"{

    entity OperationType <<entity>> <<root>>{
    }

    class OperationTypeId <<Value Object>>{
        
    }

    class OperationTypeName <<Value Object>>{
        
    }

    class EstimatedDuration <<Value Object>>{
        
    }
}

package "<<aggregate>> Appointment"{

    entity Appointment <<entity>> <<root>>{
    }

    class AppointmentId <<Value Object>>{
        
    }

    class AppointmentDateAndTime <<Value Object>>{
        
    }

    enum AppointmentStatus <<Value Object>>{
        SCHEDULED
        COMPLETED
        CANCELED
    }
}

package "<<aggregate>> SurgeryRoom"{

    entity SurgeryRoom <<entity>> <<root>>{
    }

    class RoomNumber <<Value Object>>{
        
    }

    enum RoomType <<Value Object>>{
        OPERATING_ROOM
        CONSULTATION_ROOM
        ICU
    }

    class Capacity <<Value Object>>{
        
    }

    class AssignedEquipment <<Value Object>> { 

    }

    enum CurrentStatus <<Value Object>>{
        AVAILABLE
        OCCUPIED
        UNDER_MAINTENANCE
    }

    class MaintenanceSlots <<Value Object>> {
             
    }
    
}

'User'
Username <- User
User --> Role
User --> Email

'Patient'
PatientFirstName <-- Patient
PatientLastName <-- Patient
PatientFullName <-- Patient
DateOfBirth <- Patient
Patient --> Gender
Patient ---> MedicalRecordNumber
Patient ---> PatientContactInformation
Patient --> MedicalConditions
Patient --> EmergencyContact
Patient -> AppointmentHistory
Patient ---> PatientEmail
Patient ---> PatientPhone
Patient "1" --> "0..1" User: includes

'Staff'
Staff --> StaffFirstName
Staff --> StaffLastName
Staff -> StaffFullName
StaffContactInformation <- Staff
StaffEmail <- Staff
Staff ---> LicenseNumber
Staff ---> AvailabilitySlots
Staff --> StaffPhone
Staff "1" ---> "1"User: includes
Staff "1" ---> "1" Specialization : has

'Specialization'
Specialization --> SpecializationId
Specialization --> SpecializationName

'OperationRequest'
OperationRequestId <- OperationRequest
OperationRequest --> DeadlineDate
OperationRequest --> Priority
OperationRequest "*" --> "1" Patient: of
OperationRequest "*" ---> "1" Staff: to
OperationRequest "*" ---> "1" OperationType: of

'OperationType'
OperationType --> OperationTypeId
OperationType --> OperationTypeName
OperationType -> EstimatedDuration
OperationType "*" --> "*" Specialization: has

'Appointment'
AppointmentId <- Appointment
Appointment --> AppointmentDateAndTime
Appointment --> AppointmentStatus
Appointment "1" ---> "1" OperationRequest: of
Appointment "*" ---> "1" SurgeryRoom: in

'SurgeryRoom'
RoomNumber <- SurgeryRoom
SurgeryRoom --> RoomType
SurgeryRoom --> Capacity
SurgeryRoom --> AssignedEquipment
SurgeryRoom --> CurrentStatus
SurgeryRoom  -> MaintenanceSlots

@enduml