@startuml process-view

actor "BackofficeUser" as User
participant SYS as "SARM" <<C4:System>>

activate User
User->SYS:POST /api/users/login
    activate SYS

        SYS->SYS:Login(LoginRequestDto)

        User<--SYS:200 Ok
    deactivate SYS
deactivate User
@enduml