@startuml process-view

actor "Doctor" as Doctor
participant SYS as "SARM" <<C4:System>>

activate Doctor
Doctor->SYS:PUT /api/OperationRequest/{id}
    activate SYS

        SYS->SYS:UpdateOperationRequestAsync(id,operationRequestUpdateDto)

        Doctor<--SYS:200 OK
    deactivate SYS
deactivate Doctor
@enduml