@startuml process-view
autonumber

actor "Doctor" as Doctor
participant Frontend as "Frontend" <<system (C4)>>
participant BackendDataManagement as "Backend Data Management" <<system (C4)>>

activate Doctor

    Doctor -> Frontend : asks to create an appointment

    activate Frontend

        Frontend --> Doctor : asks to input data

    deactivate Frontend

    Doctor -> Frontend : input data
    
    activate Frontend
    
        Frontend-> BackendDataManagement : POST /appointments
        activate BackendDataManagement

            Frontend <-- BackendDataManagement : 201 Created

        deactivate BackendDataManagement

    Frontend --> Doctor : shows success message
    
    deactivate Frontend
deactivate Doctor

@enduml