@startuml process-view
autonumber

actor "Admin" as Admin
participant SARM as "SARM" <<system (C4)>>

activate Admin
    Admin -> SARM : asks to list patient profiles
    activate SARM
        SARM --> Admin: shows patient profiles
    deactivate SARM
deactivate Admin

@enduml