@startuml process-view

autonumber

actor "Doctor" as Doctor
participant BackendDataManagement as "Backend Data Management" <<system (C4)>>

activate Doctor

    alt Get operation types
        Doctor-> BackendDataManagement : GET /api/operationRequests/filter

        activate BackendDataManagement

            BackendDataManagement -> BackendDataManagement : GetOperationRequestsAsync(patientId,\n operationTypeId, priority, status)

        Doctor <-- BackendDataManagement : 200 OK
        deactivate BackendDataManagement

deactivate Doctor

@enduml