@startuml level2

participant SYS as "SARM" <<C4:System>>

?o->SYS:POST /api/operationrequest
activate SYS

    SYS->SYS:AddOperationRequestAsync(creatingOperationRequestDto)

    <--SYS:201 created
deactivate SYS

@enduml