@startuml process-view
autonumber

actor "Admin" as Admin
participant BackendDataManagement as "Backend Data Management" <<system (C4)>>

activate Admin

    Admin-> BackendDataManagement : POST /api/operationtypes
    activate BackendDataManagement

        BackendDataManagement -> BackendDataManagement : AddOperationType(creatingOperationTypeDto)

        Admin <-- BackendDataManagement : 201 Created
    deactivate BackendDataManagement

deactivate Admin

@enduml