@startuml process-view
autonumber

actor "Admin" as Admin
participant Frontend as "Frontend" <<system (C4)>>
participant BackendNode as "Backend Node" <<system (C4)>>

activate Admin

    Admin -> Frontend : asks to update an allergy

    activate Frontend

        Frontend --> Admin : asks to update data

    deactivate Frontend

    Admin -> Frontend : update data
    
    activate Frontend
    
        Frontend-> BackendNode : PATCH /allergies/{id}
        activate BackendNode

            Frontend <-- BackendNode : 200 OK

        deactivate BackendNode

    Frontend --> Admin : shows success message
    
    deactivate Frontend
deactivate Admin

@enduml