@startuml process-view
autonumber

actor "Admin" as ADM
participant "Backend Data Management" as BDM

activate ADM
ADM-> BDM : PUT /api/patients/{id}
activate BDM
    BDM -> BDM : editPatientProfile(editingPatientDto)
    ADM<-- BDM : 200 OK
deactivate BDM
deactivate ADM

@enduml