@startuml process-view
autonumber
skinparam DefaultTextAlignment center
actor Admin as "Admin"
box "<<system (C4)>>\nFrontend"#LightBlue
    participant ComponentUI as "UI Component" <<component (C4)>>
    participant Component as "Component" <<component (C4)>>
    participant SRV as "Service" <<component (C4)>>
    participant HTTP as "HTTP" <<component (C4)>>
end box

box "<<system (C4)>>\nServer"
  participant Server as "Server" <<component (C4)>>
end box

activate Admin
    Admin -> ComponentUI : asks to remove an operation type
    activate ComponentUI
        ComponentUI --> Admin : asks to confirm
    deactivate ComponentUI
    Admin -> ComponentUI : confirms
    activate ComponentUI
        ComponentUI -> Component : deactivate operation type
        activate Component     
            Component -> SRV : deactivate operation type
            activate SRV
                SRV -> HTTP : delete('/operationTypes')
                activate HTTP
                    HTTP -> Server : DELETE /operationTypes
                    activate Server
                        Server --> HTTP : 200 (operationType)
                    deactivate Server
                    HTTP --> SRV : operationType
                deactivate HTTP
                SRV --> Component : operationType
            deactivate SRV
            Component --> ComponentUI : operationType
        deactivate Component
    Admin <-- ComponentUI : shows success message
    deactivate ComponentUI
deactivate Admin

@enduml