@startuml process-view
autonumber

actor "Admin" as ADM
participant "Backend Data Management" as BDM

activate ADM
    ADM -> BDM : PUT /api/staffs/{id}
    activate BDM
        BDM -> BDM : editStaffProfile(editingStaffDto)
        BDM --> ADM : 200 OK
    deactivate BDM
deactivate ADM

@enduml