@startuml process-view
autonumber

actor "BackofficeUser" as UserP
participant "UsersController" as Controller <<Controller>>
participant "UserService" as Service <<Service>>

activate UserP
UserP->Controller:POST /api/users/resetpassword
activate Controller
    
    Controller->Service:ResetPassword(RequestResetPasswordDto)
    activate Service

        note right of Service: Reset Password with Auth0

        Service-->Controller:message
    deactivate Service
    UserP<-- Controller:200 OK
deactivate Controller
@enduml 