@startuml logic-view
top to bottom direction

interface "API" as API

component "Backend Data Management" <<component>>{
    () "DB API" as DBAPI
    portin " " as PI

    component "Backend API" <<component>> <<C4 Container>>{
        portin " " as BEPI
        portout " " as BEPO
    }

    component "DataBase" <<component>> <<C4 Container>>{
        portin " " as DBPI
    }
     
}

API -- PI
PI -- BEPI 
BEPO --( DBAPI
DBPI -U- DBAPI

@enduml