@startuml process-view
autonumber

actor "Admin" as ADM
participant "Backend Data Management" as BDM

activate ADM
    ADM -> BDM : POST /api/staffs
    activate BDM
        BDM -> BDM : createStaffProfile(creatingStaffDto)
        BDM --> ADM : 201 Created
    deactivate BDM
deactivate ADM

@enduml