@startuml process-view
autonumber

actor "Doctor" as Doctor
participant SARM as "SARM" <<system (C4)>>

activate Doctor

    Doctor -> SARM : asks to update an appointment
    
    activate SARM

        SARM --> Doctor : asks to update data

    deactivate SARM

    Doctor -> SARM : update data

    activate SARM 
        SARM --> Doctor: shows success message
        
    deactivate SARM

deactivate Doctor

@enduml