@startuml process-view-2
autonumber

participant "UsersController" as Controller <<Controller>>
participant "UserService" as Service <<Service>>
participant "User" as User <<Domain>>
participant "Patient" as Patient <<Domain>>
participant "UserDto" as UserDto <<Domain>>
database "IPatientRepository" as PatientRepository <<Domain>>
database "IUserRepository" as UserRepository <<Domain>>

?o-> Controller : POST /api/users/patients

activate Controller

    Controller -> Service : addUserPatientAsync(creatingUserDto)

    activate Service

        Service -> PatientRepository : GetByEmailAsync(creatingUserDto.Email)

        activate PatientRepository

            PatientRepository --> Service : patient

        deactivate PatientRepository

        alt patient == null 

            Service --> Controller : NotFoundException

            ?o<-- Controller : 404 Not Found

        end 

        Service -> User : create(creatingUserDto.Username,creatingUserDto.Email,Role.PATIENT)

        activate User

            User --> Service : user

        deactivate User

        Service  -> UserRepository : AddAsync(user)

        activate UserRepository

            UserRepository --> Service : user

        deactivate UserRepository

        Service -> Patient : UpdateUser(user)

        Service -> PatientRepository : UpdateAsync(patient)

        activate PatientRepository

            PatientRepository -->  Service : patient
        
        deactivate PatientRepository

        Service -> UserDto : create(Username,Email,Role)

        activate UserDto

            UserDto --> Service : userDto

        deactivate UserDto

        Service --> Controller : userDto

    deactivate Service

    ?o<-- Controller : 201 Created

deactivate Controller


@enduml