@startuml process-view-2
autonumber

actor "Patient" as PatientActor
participant "UsersController" as Controller <<Controller>>
participant "UserService" as Service <<Service>>
participant "User" as User <<Domain>>
participant "Patient" as Patient <<Domain>>
participant "UserDto" as UserDto <<Domain>>
database "IPatientRepository" as PatientRepository <<Domain>>
database "IUserRepository" as UserRepository <<Domain>>

activate PatientActor

    PatientActor-> Controller : POST /api/users/patients

    activate Controller

        Controller -> Service : AddUserPatientAsync(creatingUserPatientDto)

        activate Service

            Service -> PatientRepository : GetByEmailAsync(creatingUserPatientDto.Email)

            activate PatientRepository

                PatientRepository --> Service : patient

            deactivate PatientRepository

            alt patient == null 

                Service --> Controller : NullReferenceException

                PatientActor <-- Controller : 404 Not Found

            else 

                Service -> User : create(creatingUserPatientDto.Email,creatingUserPatientDto.Email,Role.PATIENT)

                activate User

                    User --> Service : user

                deactivate User

                Service  -> UserRepository : AddAsync(user)

                activate UserRepository

                    UserRepository --> Service : user

                deactivate UserRepository

                Service -> Patient : UpdateUser(user)

                Service -> PatientRepository : UpdateAsync(patient)

                activate PatientRepository

                    PatientRepository -->  Service : patient
                
                deactivate PatientRepository

                Note  right of Service: Add user in the auth0 api \nand send email by auth0 for verification email

                Service -> UserDto : create(user.Username,user.Email,user.Role)

                activate UserDto

                    UserDto --> Service : userDto

                deactivate UserDto

                Service --> Controller : userDto

            end

        deactivate Service

        PatientActor <-- Controller : 201 Created

    deactivate Controller

deactivate PatientActor


@enduml