@startuml process-view
autonumber

actor "Patient" as Patient
participant "Server" as Server
participant "Database" as Database

activate Patient

    Patient-> Server : POST /api/users/patients

    activate Server

        Server -> Database : get patient
        
        activate Database

            Database --> Server : patient

        deactivate Database

        Server -> Database : save user
        
        activate Database

            Database --> Server : user

        deactivate Database

        Server -> Database : update patient
        
        activate Database

            Database --> Server : patient

        deactivate Database

        Patient <-- Server : 201 Created

    deactivate Server
deactivate Patient

@enduml