@startuml process-view
autonumber

actor "Admin" as ADM
participant "Backend Data Management" as BDM

activate ADM
ADM-> BDM : POST /api/patients/filter
activate BDM
    BDM -> BDM : listPatientProfiles(filter)
    ADM<-- BDM : 200 List of patients
deactivate BDM
deactivate ADM

@enduml