@startuml process-view
autonumber
skinparam DefaultTextAlignment center
actor Admin as "Admin"

box "<<system (C4)>>\nFrontend"#LightBlue
    participant ComponentUI as "UI Component" <<component (C4)>>
    participant Component as "Component" <<component (C4)>>
    participant Model as "Model" <<component (C4)>>
    participant Service as "Service" <<component (C4)>>
    participant HTTP as "HTTP" <<component (C4)>>
end box

box "<<system (C4)>>\nBackend Node"
    participant Router as "AllergyRouter"<<Router>>
    participant Controller as "AllergyController"<<Controller>>
    participant Service_ as "AllergyService"<<Service>>
    participant Allergy as "Allergy"<<Domain>>
    participant AllergyMap as "AllergyMap"<<Mapper>>
    database AllergyRepo as "AllergyRepo"<<Domain>>
end box

activate Admin
    Admin -> ComponentUI : asks to update an allergy

    activate ComponentUI

        ComponentUI --> Admin : asks to update data

    deactivate ComponentUI

    Admin -> ComponentUI : update data

    activate ComponentUI
        ComponentUI -> Component : update an allergy

        activate Component
            Component -> Model** : create
            
            Component -> Service : update new allergy

            activate Service

                Service -> HTTP : patch('/allergies/{id}')

                activate HTTP

                    HTTP -> Router : PATCH /allergies/{id}
                    activate Router

                        Router -> Controller : updateAllergy(req,res,next)

                        activate Controller

                            Controller -> Service_ : updateAllergy(allergyDto)
                            
                            activate Service_

                                Service_ -> AllergyRepo : findByDomainId(allergyDTO.id)

                                activate AllergyRepo

                                    AllergyRepo --> Service_ : allergy

                                deactivate AllergyRepo

                                alt allergyDTO.designation != null

                                    Service_ -> Allergy : allergy.designation(allergyDTO.designation)

                                end

                                                                                                 alt allergyDTO.description != null

                                    Service_ -> Allergy : allergy.description(allergyDTO.description)

                                end

                                Service_ -> AllergyRepo : save(allergy)

                                Service_ -> AllergyMap : toDTO(allergy)

                                activate AllergyMap

                                    AllergyMap --> Service_ : allergyDTO

                                deactivate AllergyMap
                                
                                Service_ --> Controller : allergyDTO

                            deactivate Service_
                            Controller --> Router : allergyDTO

                        deactivate Controller
                        Router --> HTTP : 200 (allergy)

                    deactivate Router
                    HTTP --> Service : allergy

                deactivate HTTP
                Service --> Component : allergy

            deactivate Service
            Component --> ComponentUI : allergy

        deactivate Component
    Admin <-- ComponentUI : shows success message
    
    deactivate ComponentUI
deactivate Admin
@enduml