@startuml process-view
autonumber

actor "Admin" as Admin
participant SARM as "SARM" <<system (C4)>>

activate Admin

    Admin -> SARM : asks to list operation types
    
    activate SARM

        SARM --> Admin: shows operation types
        
    deactivate SARM

deactivate Admin

@enduml