@startuml process-view

actor "BackofficeUser" as BackofficeUser
participant SYS as "SARM" <<C4:System>>

activate BackofficeUser
BackofficeUser->SYS:POST /api/user/resetpassword
activate SYS

    SYS-->SYS:RequestResetPassword(RequestResetPasswordDto)

    BackofficeUser<--SYS:200 OK
deactivate SYS
deactivate BackofficeUser
@enduml